name: Deploy to GitHub Pages

on:
  push:
    branches: [ main ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      pages: write
      id-token: write

    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    steps:
      - name: Checkout do código
        uses: actions/checkout@v4

      - name: Configurar Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Instalar PNPM
        run: npm install -g pnpm

      - name: Verificar versão do PNPM
        run: pnpm --version

      - name: Instalar dependências
        run: pnpm install

      - name: Rodar build
        run: pnpm run build

      - name: Configurar GitHub Pages
        uses: actions/configure-pages@v4

      - name: Enviar artefato para GitHub Pages
        uses: actions/upload-pages-artifact@v3
        with:
          path: './dist'

      - name: Fazer deploy para o GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
